### ISSUE TITLE
ビューワー画面で画像がサンプルのまま

### ISSUE THREAD

**Issue by mehm8128** [digicon-trap1-2023/frontend#47]
いい感じのにしたい
サーバーから取っているわけではないので、フロントで画像を持ってパス指定
![image](https://github.com/digicon-trap1-2023/frontend/assets/83744975/f10f0499-b221-426b-8ada-0a6f94ec3017)

**Comment by nokhnaton** [comment]
直しました

**Comment by mehm8128** [comment]
ありがとうございますー
pikachuくんのやつも入れてよさそう(後で入ってなかったら入れます)
